export const LOCAL_STORAGE_KEYS = {
    USER_DATA: 'userData',
    CURRENT_SELECTED_WALLET: 'currentSelectedWallet',
    UNFINISHED_KRC20_ACTIONS: 'unfinishedKRC20Actions',
}

export const KASPA_NETWORKS = {
    MAINNET: 'mainnet',
    TESTNET10: 'testnet-10'
}

export const DEFAULT_DERIVED_PATH = "m/44'/111111'/0'/0/0";

export const ERROR_CODES = {
    WALLET_ACTION: {
        WALLET_NOT_SELECTED: 1001,
        INVALID_ACTION_TYPE: 1002,
        INVALID_AMOUNT: 1003,
        INVALID_ADDRESS: 1004,
        INSUFFICIENT_BALANCE: 1005,
        USER_REJECTED: 1006,
        TICKER_NOT_FOUND: 1007,
        TOKEN_NOT_IN_MINTABLE_STATE: 1008,
        NO_UTXOS_TO_COMPOUND: 1009,
        REVEAL_WITH_NO_COMMIT_ACTION: 1010,

    }
}